import { AppLayout } from "@/components/AppLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Shield,
  Scale,
  FileText,
  Lock,
  UserCheck,
  Phone,
  AlertTriangle,
  CheckCircle,
} from "lucide-react";

const TOC = [
  { id: "educational", label: "Educational Notice" },
  { id: "no-guarantee", label: "No Guarantee Policy" },
  { id: "fcra", label: "FCRA Rights" },
  { id: "croa", label: "CROA Disclosure" },
  { id: "cso", label: "Texas CSO Notice" },
  { id: "security", label: "Data Security" },
  { id: "responsibilities", label: "User Responsibilities" },
  { id: "contact", label: "Contact & Cancellation" },
];

const FCRA_RIGHTS = [
  {
    title: "Right to Dispute",
    description: "You have the right to dispute inaccurate information on your credit report directly with the credit bureau.",
    icon: FileText,
  },
  {
    title: "Free Annual Reports",
    description: "You are entitled to one free credit report per year from each bureau through AnnualCreditReport.com.",
    icon: CheckCircle,
  },
  {
    title: "30-Day Investigation",
    description: "Credit bureaus must investigate your dispute within 30 days and notify you of the results.",
    icon: Scale,
  },
  {
    title: "Right to Know",
    description: "You have the right to know what is in your credit file, including who has accessed it.",
    icon: UserCheck,
  },
  {
    title: "Removal of Unverified Info",
    description: "If disputed information cannot be verified, the bureau must remove or correct it.",
    icon: Shield,
  },
  {
    title: "Sue for Violations",
    description: "You may sue in federal or state court if a credit reporting agency, user, or provider violates the FCRA.",
    icon: AlertTriangle,
  },
];

export default function CompliancePage() {
  return (
    <AppLayout>
      <div className="max-w-4xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-serif mb-2">Legal & Compliance</h1>
          <p className="text-muted-foreground">
            Important legal disclosures, your rights, and our compliance commitments.
          </p>
        </div>

        {/* Table of Contents */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="text-sm font-medium">Table of Contents</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
              {TOC.map((item) => (
                <a
                  key={item.id}
                  href={`#${item.id}`}
                  className="text-sm text-blue-400 hover:text-blue-300 hover:underline p-2 rounded-lg hover:bg-muted/30 transition-colors"
                  onClick={(e) => {
                    e.preventDefault();
                    document.getElementById(item.id)?.scrollIntoView({ behavior: "smooth" });
                  }}
                >
                  {item.label}
                </a>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Educational Notice */}
        <section id="educational" className="mb-8">
          <Card className="border-primary/30">
            <CardHeader>
              <CardTitle className="font-serif text-xl flex items-center gap-2">
                <Shield className="h-5 w-5 text-primary" />
                Educational Notice
              </CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-3 leading-relaxed">
              <p>
                Sterling Credit Solutions ("SCS") is an <strong className="text-foreground">educational platform</strong> designed
                to help consumers understand their credit reports and exercise their rights under federal and state law.
              </p>
              <p>
                SCS does <strong className="text-foreground">not</strong> provide legal advice, financial advice,
                tax advice, or credit repair services. The tools, templates, and information provided are for
                educational purposes only.
              </p>
              <p>
                All dispute letters generated by SCS are educational templates. You are solely responsible for
                reviewing, personalizing, and submitting any correspondence to credit bureaus or creditors.
              </p>
            </CardContent>
          </Card>
        </section>

        {/* No Guarantee Policy */}
        <section id="no-guarantee" className="mb-8">
          <Card>
            <CardHeader>
              <CardTitle className="font-serif text-xl flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-primary" />
                No Guarantee Policy
              </CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-3 leading-relaxed">
              <p>
                Sterling Credit Solutions makes <strong className="text-foreground">no guarantee</strong> that:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Your credit score will increase</li>
                <li>Any specific item will be removed from your credit report</li>
                <li>Dispute letters will result in any particular outcome</li>
                <li>Any specific financial result will occur from using our tools</li>
              </ul>
              <p>
                Accurate negative information generally cannot be removed from your credit report through disputing.
                Only inaccurate, incomplete, or unverifiable information may be corrected or removed through the
                dispute process under FCRA.
              </p>
            </CardContent>
          </Card>
        </section>

        {/* FCRA Rights */}
        <section id="fcra" className="mb-8">
          <h2 className="font-serif text-2xl mb-4">Your FCRA Rights</h2>
          <p className="text-sm text-muted-foreground mb-6">
            The Fair Credit Reporting Act (15 U.S.C. § 1681 et seq.) provides you with important rights
            regarding your credit information.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {FCRA_RIGHTS.map((right) => (
              <Card key={right.title}>
                <CardContent className="p-5">
                  <right.icon className="h-5 w-5 text-primary mb-3" />
                  <p className="text-sm font-medium mb-1">{right.title}</p>
                  <p className="text-xs text-muted-foreground leading-relaxed">{right.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        {/* CROA Disclosure */}
        <section id="croa" className="mb-8">
          <Card className="border-primary/30">
            <CardHeader>
              <CardTitle className="font-serif text-xl flex items-center gap-2">
                <Scale className="h-5 w-5 text-primary" />
                CROA Disclosure
              </CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-3 leading-relaxed">
              <p className="text-xs uppercase tracking-wider text-primary font-medium">
                Credit Repair Organizations Act (15 U.S.C. § 1679)
              </p>
              <div className="p-4 bg-muted/30 rounded-lg space-y-3 text-xs leading-relaxed">
                <p>
                  You have a right to dispute inaccurate information in your credit report by contacting
                  the credit bureau directly. However, neither you nor any "credit repair" company or
                  credit repair organization has the right to have accurate, current, and verifiable
                  information removed from your credit report. The credit bureau must remove accurate,
                  negative information from your report only if it is over 7 years old. Bankruptcy
                  information can be reported for 10 years.
                </p>
                <p>
                  You have a right to obtain a copy of your credit report from a credit bureau. You may
                  be charged a reasonable fee. There is no fee, however, if you have been turned down
                  for credit, employment, insurance, or a rental dwelling because of information in your
                  credit report within the preceding 60 days. The credit bureau must provide someone to
                  help you interpret the information in your credit report. You are entitled to receive
                  a free copy of your credit report if you are unemployed and intend to apply for
                  employment in the next 60 days, if you are a recipient of public welfare assistance,
                  or if you have reason to believe that there is inaccurate information in your credit
                  report due to fraud.
                </p>
                <p>
                  You have a right to sue a credit repair organization that violates the Credit Repair
                  Organization Act. This law prohibits deceptive practices by credit repair organizations.
                </p>
                <p>
                  You have the right to cancel your contract with any credit repair organization for any
                  reason within 3 business days from the date you signed it.
                </p>
                <p>
                  Credit bureaus are required to follow reasonable procedures to make sure that the
                  information they report is accurate. However, mistakes may occur.
                </p>
              </div>
            </CardContent>
          </Card>
        </section>

        {/* Texas CSO Notice */}
        <section id="cso" className="mb-8">
          <Card>
            <CardHeader>
              <CardTitle className="font-serif text-xl flex items-center gap-2">
                <FileText className="h-5 w-5 text-primary" />
                Texas Credit Services Organization Notice
              </CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-3 leading-relaxed">
              <p>
                Sterling Credit Solutions operates as a Credit Services Organization ("CSO") under
                Texas Finance Code, Chapter 393.
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong className="text-foreground">Right to Cancel:</strong> You may cancel any contract
                  or agreement with SCS within 3 business days from the date you signed it.
                </li>
                <li>
                  <strong className="text-foreground">No Advance Payment:</strong> No payment is required
                  before services are fully performed.
                </li>
                <li>
                  <strong className="text-foreground">Bond:</strong> SCS maintains a surety bond as required
                  by Texas law for the protection of consumers.
                </li>
                <li>
                  <strong className="text-foreground">Registration:</strong> SCS is registered with the
                  Texas Secretary of State as required by law.
                </li>
              </ul>
            </CardContent>
          </Card>
        </section>

        {/* Data Security */}
        <section id="security" className="mb-8">
          <Card>
            <CardHeader>
              <CardTitle className="font-serif text-xl flex items-center gap-2">
                <Lock className="h-5 w-5 text-primary" />
                Data Security
              </CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-3 leading-relaxed">
              <p>Sterling Credit Solutions takes the security of your data seriously:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>All data is transmitted using TLS/SSL encryption</li>
                <li>Uploaded credit reports are stored in encrypted, private storage buckets</li>
                <li>Access to your data is restricted to your authenticated account only</li>
                <li>We do not sell, share, or distribute your personal information to third parties</li>
                <li>You may request deletion of your data at any time</li>
              </ul>
            </CardContent>
          </Card>
        </section>

        {/* User Responsibilities */}
        <section id="responsibilities" className="mb-8">
          <Card>
            <CardHeader>
              <CardTitle className="font-serif text-xl flex items-center gap-2">
                <UserCheck className="h-5 w-5 text-primary" />
                User Responsibilities
              </CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-3 leading-relaxed">
              <p>As a user of Sterling Credit Solutions, you agree that:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>You will only upload your own credit reports</li>
                <li>You will review all dispute letters before sending them</li>
                <li>You understand that SCS provides educational tools, not legal advice</li>
                <li>You are solely responsible for all actions taken based on information from SCS</li>
                <li>You will not use SCS tools to submit false or fraudulent disputes</li>
                <li>You understand that results are not guaranteed</li>
              </ul>
            </CardContent>
          </Card>
        </section>

        {/* Contact & Cancellation */}
        <section id="contact" className="mb-8">
          <Card>
            <CardHeader>
              <CardTitle className="font-serif text-xl flex items-center gap-2">
                <Phone className="h-5 w-5 text-primary" />
                Contact & Cancellation
              </CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-3 leading-relaxed">
              <p>
                To cancel services, request data deletion, or contact us for any reason:
              </p>
              <div className="p-4 bg-muted/30 rounded-lg space-y-2">
                <p><strong className="text-foreground">Sterling Credit Solutions</strong></p>
                <p>Alice, TX</p>
                <p>Phone: (361) 660-3993</p>
                <p>Website: txscs.com</p>
              </div>
              <p>
                You may cancel services within 3 business days of signing any service agreement.
                To cancel, contact us by phone or in writing at the address above.
              </p>
            </CardContent>
          </Card>
        </section>
      </div>
    </AppLayout>
  );
}
